<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <!-- 패키지 이름: CMakeLists.txt의 project() 이름과 같아야 합니다 -->
  <name>turtlebot_qr</name>
  <version>0.0.1</version>
  <description>Turtlebot3 QR Navigation Package</description>
  
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <!-- 빌드 툴 지정 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- 의존성 패키지 목록 -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>
  <depend>opencv</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>